### ISSUE TITLE
Using ANCS

### ISSUE THREAD

**Issue by drewcassidy** [ARMmbed/ble#179]
Will this library support ANCS (Apple Notification Center Service) in the future?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2265

**Comment by pan-** [comment]
ANCS will not be directly supported by this library but we already have a library built on top of BLE which manage ANCS: https://github.com/ARMmbed/ble-ancs-client .

**Comment by pan-** [comment]
Since this is not an issue, I'm closing this.
