### ISSUE TITLE
Return error on write request when locked

### ISSUE THREAD

**Issue by schilit** [ARMmbed/ble#19]
is there a way for
```
 void onDataWritten(const GattCharacteristicWriteCBParams *params)
```

to return a GATT error code (see  [error codes](https://github.com/google/uribeacon/blob/master/specification/ConfigService.md#13-error-codes)) when
the write attempt is made on a locked device?

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-867

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1038

**Comment by rgrover** [comment]
I believe we have solved this problem using writeAuthorization callbacks.
