### ISSUE TITLE
add support for Eddystone

### ISSUE THREAD

**Issue by prusnak** [ARMmbed/ble#57]
Having a service similar to `ble/services/iBeacon.h` but for Eddystone would be nice.

Eddystone protocol specification: https://github.com/google/eddystone/blob/master/protocol-specification.md

Sample source code: http://qiita.com/KazuyukiEguchi/items/a939a9aeae2d36c51df8

**Comment by rgrover** [comment]
we're working on it.

**Comment by rgrover** [comment]
@BlackstoneEngineering : could you please update and publish a demo on mbed.org around Eddystone. Please note that EddystoneService has now been added to ble/services/

**Comment by BlackstoneEngineering** [comment]
Waiting on @rgrover, I can release the preliminary version, but I would really like to use pull request https://github.com/ARMmbed/ble/pull/61 to make an eddystone service that plays nice with other services. The current example clobbers any other service on the device.

**Comment by rgrover** [comment]
There's an initial Eddystone service in BLE_API. It was borrowed from work done by @BlackstoneEngineering. I made some changes to the initialization code (removed ble.shutdown() and ble.init()); it is very likely that the current state needs some more work and testing before it can be published as a demo.

**Comment by BlackstoneEngineering** [comment]
I have removed the changes (as they broke the service, will revisit at a later date to re-impliment) and submitted a pull request here: https://github.com/ARMmbed/ble/pull/66

**Comment by BlackstoneEngineering** [comment]
Here ya go : https://developer.mbed.org/teams/Bluetooth-Low-Energy/code/BLE_EddystoneBeacon_Service/

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-861

**Comment by BlackstoneEngineering** [comment]
@rainierwolfcastle this is a public facing repository, please dont post Jira tickets here.

**Comment by rgrover** [comment]
the eddystone service is now a part of the standard services supported by BLE_API.

**Comment by prusnak** [comment]
Great! Thanks!
