### ISSUE TITLE
Wrong include file in HealthTermometerService.h:20:17

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/ble#86]
/work/iot/ble-examples/BLE_Thermometer/yotta_modules/ble/ble/services/HealthThermometerService.h:20:17: fatal error: BLE.h: No such file or directory
 #include "BLE.h"
                 ^
compilation terminated.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1090

**Comment by rgrover** [comment]
@LiyouZhou Could you please check with @andresag01 why you are having difficulty building this example?

**Comment by andresag01** [comment]
It seems that the include path of BLE.h within the HealthThermometerService.h file should be replaced by "ble/BLE.h".

**Comment by rgrover** [comment]
could you please do this, Andres, and submit a pull request?

**Comment by andresag01** [comment]
Submitted pull request to 'develop' branch to solve this issue.

**Comment by rgrover** [comment]
this will be committed to master with the next release.
